# Generated by Django 4.2 on 2024-05-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescreen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
